#!/usr/bin/perl -w
# Writes the last line of one.txt to last.txt.
open(INFILE, "<", "one.txt")
    or die "could not open INFILE: $!\n";
my $lastLine;
while(my $line = <INFILE>) {
    $lastLine = $line;
}
close(INFILE);
open(OUTFILE, ">", "last.txt");
print OUTFILE $lastLine;
close(OUTFILE);

