#!/usr/bin/perl -w
# for each valid file in the command arguments, output the name 
# of the file and its contents
print "Files:", "@ARGV\n";
foreach my $file (@ARGV) {
    next unless ( -r $file );  #skip an invalid file
    print ">>> $file \n";
    $output = `cat $file`;     #save the stdout of cat in a 
                               #string variable
    print $output;
}
print "\n";

